version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=6a1149f1
      - MYSQL_DATABASE=meetphp
      - MYSQL_USER=beginner
      - MYSQL_PASSWORD=foofoofoo
